name: "[CD] Continuous Delivery"

# Whenever there is a commit or an open Pull Request
# on: 
#     push: 
#         branches: [main]

on:
    pull_request:
        types: [opened, synchronize]

env:
    VERCEL_PROJECT_NAME: crud
    VERCEL_ORG_ID: team_CcTwMpqqgQpPm5rRs3f4foGK
    VERCEL_PROJECT_ID: prj_4ruixftIoKQ1HEhexYlLaAhZyH9O

jobs: 
    deploy: 
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v3

            - name: "Debug"
              run: |
                ls -la 
            - name: "Install Dependencies"
              run: "npm i"
            - name: "Vercel Deploy"
              run: "vercel --prod --token=${{ secrets.VERCEL_TOKEN }}"
